---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: macvlan-networkpolicies.k8s.cni.cncf.io
spec:
  group: k8s.cni.cncf.io
  scope: Namespaced
  names:
    plural: macvlan-networkpolicies
    singular: macvlan-networkpolicy
    kind: MacvlanNetworkPolicy
    shortNames:
    - macvlan-policy
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                podSelector:
                  type: object
                  properties:
                    matchExpressions:
                      items:
                        properties:
                          key:
                            type: string
                          operator:
                            type: string
                          values:
                            items:
                              type: string
                            type: array
                        required:
                        - key
                        - operator
                        type: object
                      type: array
                    matchLabels:
                      additionalProperties:
                        type: string
                      type: object
                ingress:
                  items:
                    type: object
                    properties:
                      ports:
                        items:
                          type: object
                          properties:
                            protocol:
                              type: string
                            port:
                              anyOf:
                                - type: integer
                                - type: string
                              x-kubernetes-int-or-string: true
                        type: array
                      from:
                        items:
                          type: object
                          properties:
                            podSelector:
                              type: object
                              properties:
                                matchExpressions:
                                  items:
                                    properties:
                                      key:
                                        type: string
                                      operator:
                                        type: string
                                      values:
                                        items:
                                          type: string
                                        type: array
                                    required:
                                    - key
                                    - operator
                                    type: object
                                  type: array
                                matchLabels:
                                  additionalProperties:
                                    type: string
                                  type: object
                            namespaceSelector:
                              type: object
                              properties:
                                matchExpressions:
                                  items:
                                    properties:
                                      key:
                                        type: string
                                      operator:
                                        type: string
                                      values:
                                        items:
                                          type: string
                                        type: array
                                    required:
                                    - key
                                    - operator
                                    type: object
                                  type: array
                                matchLabels:
                                  additionalProperties:
                                    type: string
                                  type: object
                            ipBlock:
                              type: object
                              properties:
                                cidr:
                                  type: string
                                except:
                                  items:
                                    type: string
                                  type: array
                        type: array
                  type: array
                egress:
                  items:
                    type: object
                    properties:
                      ports:
                        items:
                          type: object
                          properties:
                            protocol:
                              type: string
                            port:
                              anyOf:
                                - type: integer
                                - type: string
                              x-kubernetes-int-or-string: true
                        type: array
                      to:
                        items:
                          type: object
                          properties:
                            podSelector:
                              type: object
                              properties:
                                matchExpressions:
                                  items:
                                    properties:
                                      key:
                                        type: string
                                      operator:
                                        type: string
                                      values:
                                        items:
                                          type: string
                                        type: array
                                    required:
                                    - key
                                    - operator
                                    type: object
                                  type: array
                                matchLabels:
                                  additionalProperties:
                                    type: string
                                  type: object
                            namespaceSelector:
                              type: object
                              properties:
                                matchExpressions:
                                  items:
                                    properties:
                                      key:
                                        type: string
                                      operator:
                                        type: string
                                      values:
                                        items:
                                          type: string
                                        type: array
                                    required:
                                    - key
                                    - operator
                                    type: object
                                  type: array
                                matchLabels:
                                  additionalProperties:
                                    type: string
                                  type: object
                            ipBlock:
                              type: object
                              properties:
                                cidr:
                                  type: string
                                except:
                                  items:
                                    type: string
                                  type: array
                        type: array
                  type: array
                policyTypes:
                  type: string
